// flow-typed signature: 611ff4b4683a56ce06b369d94f152f01
// flow-typed version: <<STUB>>/disable-output-webpack-plugin_v^1.0.1/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'disable-output-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'disable-output-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'disable-output-webpack-plugin/index' {
  declare module.exports: $Exports<'disable-output-webpack-plugin'>;
}
declare module 'disable-output-webpack-plugin/index.js' {
  declare module.exports: $Exports<'disable-output-webpack-plugin'>;
}
