// flow-typed signature: 4f1eb29e7dceb1f427ba60dff879e128
// flow-typed version: <<STUB>>/jest-pnp-resolver_v1.0.1/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-pnp-resolver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-pnp-resolver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jest-pnp-resolver/index' {
  declare module.exports: $Exports<'jest-pnp-resolver'>;
}
declare module 'jest-pnp-resolver/index.js' {
  declare module.exports: $Exports<'jest-pnp-resolver'>;
}
