// flow-typed signature: 953e0d5a99fe41dbf1d699b7cebf0096
// flow-typed version: <<STUB>>/query-params_v0.0.1/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'query-params'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'query-params' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'query-params/karma.conf' {
  declare module.exports: any;
}

declare module 'query-params/query-params.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'query-params/index' {
  declare module.exports: $Exports<'query-params'>;
}
declare module 'query-params/index.js' {
  declare module.exports: $Exports<'query-params'>;
}
declare module 'query-params/karma.conf.js' {
  declare module.exports: $Exports<'query-params/karma.conf'>;
}
declare module 'query-params/query-params.test.js' {
  declare module.exports: $Exports<'query-params/query-params.test'>;
}
