// flow-typed signature: f555739cd90dd91566bc8b9391cda261
// flow-typed version: <<STUB>>/react-dates-onidata_vhttps://github.com/onidata/react-dates.git#package/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dates-onidata'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dates-onidata' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dates-onidata/constants' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/CalendarDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/CalendarIcon' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/CalendarMonth' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/CalendarMonthGrid' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/CalendarWeek' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/ChevronDown' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/ChevronUp' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/CloseButton' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/CustomizableCalendarDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/DateInput' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/DateRangePicker' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/DateRangePickerInput' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/DateRangePickerInputController' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/DayPicker' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/DayPickerKeyboardShortcuts' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/DayPickerNavigation' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/DayPickerRangeController' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/DayPickerSingleDateController' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/KeyboardShortcutRow' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/LeftArrow' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/RightArrow' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/SingleDatePicker' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/SingleDatePickerInput' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/components/SingleDatePickerInputController' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/constants' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/defaultPhrases' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/initialize' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/shapes/AnchorDirectionShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/shapes/CalendarInfoPositionShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/shapes/DateRangePickerShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/shapes/DayOfWeekShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/shapes/DisabledShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/shapes/FocusedInputShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/shapes/IconPositionShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/shapes/ModifiersShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/shapes/OpenDirectionShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/shapes/OrientationShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/shapes/ScrollableOrientationShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/shapes/SingleDatePickerShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/theme/DefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/calculateDimension' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/disableScroll' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/getActiveElement' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/getCalendarDaySettings' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/getCalendarMonthWeeks' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/getCalendarMonthWidth' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/getDetachedContainerStyles' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/getInputHeight' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/getNumberOfCalendarMonthWeeks' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/getPhrase' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/getPhrasePropTypes' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/getPooledMoment' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/getPreviousMonthMemoLast' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/getResponsiveContainerStyles' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/getSelectedDateOffset' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/getTransformStyles' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/getVisibleDays' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/isAfterDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/isBeforeDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/isDayVisible' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/isInclusivelyAfterDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/isInclusivelyBeforeDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/isNextDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/isNextMonth' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/isPrevMonth' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/isSameDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/isSameMonth' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/isTransitionEndSupported' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/modifiers' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/noflip' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/registerCSSInterfaceWithDefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/registerInterfaceWithDefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/toISODateString' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/toISOMonthString' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/toLocalizedDateString' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/esm/utils/toMomentObject' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/initialize' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/karma.conf' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/CalendarDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/CalendarIcon' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/CalendarMonth' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/CalendarMonthGrid' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/CalendarWeek' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/ChevronDown' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/ChevronUp' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/CloseButton' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/CustomizableCalendarDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/DateInput' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/DateRangePicker' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/DateRangePickerInput' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/DateRangePickerInputController' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/DayPicker' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/DayPickerKeyboardShortcuts' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/DayPickerNavigation' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/DayPickerRangeController' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/DayPickerSingleDateController' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/KeyboardShortcutRow' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/LeftArrow' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/RightArrow' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/SingleDatePicker' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/SingleDatePickerInput' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/components/SingleDatePickerInputController' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/constants' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/defaultPhrases' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/initialize' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/shapes/AnchorDirectionShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/shapes/CalendarInfoPositionShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/shapes/DateRangePickerShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/shapes/DayOfWeekShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/shapes/DisabledShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/shapes/FocusedInputShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/shapes/IconPositionShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/shapes/ModifiersShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/shapes/OpenDirectionShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/shapes/OrientationShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/shapes/ScrollableOrientationShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/shapes/SingleDatePickerShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/theme/DefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/calculateDimension' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/disableScroll' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/getActiveElement' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/getCalendarDaySettings' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/getCalendarMonthWeeks' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/getCalendarMonthWidth' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/getDetachedContainerStyles' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/getInputHeight' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/getNumberOfCalendarMonthWeeks' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/getPhrase' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/getPhrasePropTypes' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/getPooledMoment' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/getPreviousMonthMemoLast' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/getResponsiveContainerStyles' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/getSelectedDateOffset' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/getTransformStyles' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/getVisibleDays' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/isAfterDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/isBeforeDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/isDayVisible' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/isInclusivelyAfterDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/isInclusivelyBeforeDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/isNextDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/isNextMonth' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/isPrevMonth' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/isSameDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/isSameMonth' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/isTransitionEndSupported' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/modifiers' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/noflip' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/registerCSSInterfaceWithDefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/registerInterfaceWithDefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/toISODateString' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/toISOMonthString' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/toLocalizedDateString' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/lib/utils/toMomentObject' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/scripts/buildCSS' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/scripts/pure-component-fallback' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/scripts/renderAllComponents' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/CalendarDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/CalendarIcon' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/CalendarMonth' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/CalendarMonthGrid' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/CalendarWeek' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/ChevronDown' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/ChevronUp' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/CloseButton' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/CustomizableCalendarDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/DateInput' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/DateRangePicker' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/DateRangePickerInput' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/DateRangePickerInputController' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/DayPicker' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/DayPickerKeyboardShortcuts' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/DayPickerNavigation' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/DayPickerRangeController' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/DayPickerSingleDateController' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/KeyboardShortcutRow' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/LeftArrow' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/RightArrow' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/SingleDatePicker' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/SingleDatePickerInput' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/components/SingleDatePickerInputController' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/constants' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/defaultPhrases' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/initialize' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/shapes/AnchorDirectionShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/shapes/CalendarInfoPositionShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/shapes/DateRangePickerShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/shapes/DayOfWeekShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/shapes/DisabledShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/shapes/FocusedInputShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/shapes/IconPositionShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/shapes/ModifiersShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/shapes/OpenDirectionShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/shapes/OrientationShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/shapes/ScrollableOrientationShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/shapes/SingleDatePickerShape' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/theme/DefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/calculateDimension' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/disableScroll' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/getActiveElement' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/getCalendarDaySettings' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/getCalendarMonthWeeks' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/getCalendarMonthWidth' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/getDetachedContainerStyles' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/getInputHeight' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/getNumberOfCalendarMonthWeeks' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/getPhrase' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/getPhrasePropTypes' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/getPooledMoment' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/getPreviousMonthMemoLast' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/getResponsiveContainerStyles' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/getSelectedDateOffset' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/getTransformStyles' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/getVisibleDays' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/isAfterDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/isBeforeDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/isDayVisible' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/isInclusivelyAfterDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/isInclusivelyBeforeDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/isNextDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/isNextMonth' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/isPrevMonth' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/isSameDay' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/isSameMonth' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/isTransitionEndSupported' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/modifiers' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/noflip' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/registerCSSInterfaceWithDefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/registerInterfaceWithDefaultTheme' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/toISODateString' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/toISOMonthString' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/toLocalizedDateString' {
  declare module.exports: any;
}

declare module 'react-dates-onidata/src/utils/toMomentObject' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dates-onidata/constants.js' {
  declare module.exports: $Exports<'react-dates-onidata/constants'>;
}
declare module 'react-dates-onidata/esm/components/CalendarDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/CalendarDay'>;
}
declare module 'react-dates-onidata/esm/components/CalendarIcon.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/CalendarIcon'>;
}
declare module 'react-dates-onidata/esm/components/CalendarMonth.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/CalendarMonth'>;
}
declare module 'react-dates-onidata/esm/components/CalendarMonthGrid.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/CalendarMonthGrid'>;
}
declare module 'react-dates-onidata/esm/components/CalendarWeek.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/CalendarWeek'>;
}
declare module 'react-dates-onidata/esm/components/ChevronDown.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/ChevronDown'>;
}
declare module 'react-dates-onidata/esm/components/ChevronUp.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/ChevronUp'>;
}
declare module 'react-dates-onidata/esm/components/CloseButton.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/CloseButton'>;
}
declare module 'react-dates-onidata/esm/components/CustomizableCalendarDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/CustomizableCalendarDay'>;
}
declare module 'react-dates-onidata/esm/components/DateInput.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/DateInput'>;
}
declare module 'react-dates-onidata/esm/components/DateRangePicker.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/DateRangePicker'>;
}
declare module 'react-dates-onidata/esm/components/DateRangePickerInput.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/DateRangePickerInput'>;
}
declare module 'react-dates-onidata/esm/components/DateRangePickerInputController.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/DateRangePickerInputController'>;
}
declare module 'react-dates-onidata/esm/components/DayPicker.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/DayPicker'>;
}
declare module 'react-dates-onidata/esm/components/DayPickerKeyboardShortcuts.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/DayPickerKeyboardShortcuts'>;
}
declare module 'react-dates-onidata/esm/components/DayPickerNavigation.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/DayPickerNavigation'>;
}
declare module 'react-dates-onidata/esm/components/DayPickerRangeController.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/DayPickerRangeController'>;
}
declare module 'react-dates-onidata/esm/components/DayPickerSingleDateController.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/DayPickerSingleDateController'>;
}
declare module 'react-dates-onidata/esm/components/KeyboardShortcutRow.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/KeyboardShortcutRow'>;
}
declare module 'react-dates-onidata/esm/components/LeftArrow.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/LeftArrow'>;
}
declare module 'react-dates-onidata/esm/components/RightArrow.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/RightArrow'>;
}
declare module 'react-dates-onidata/esm/components/SingleDatePicker.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/SingleDatePicker'>;
}
declare module 'react-dates-onidata/esm/components/SingleDatePickerInput.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/SingleDatePickerInput'>;
}
declare module 'react-dates-onidata/esm/components/SingleDatePickerInputController.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/components/SingleDatePickerInputController'>;
}
declare module 'react-dates-onidata/esm/constants.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/constants'>;
}
declare module 'react-dates-onidata/esm/defaultPhrases.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/defaultPhrases'>;
}
declare module 'react-dates-onidata/esm/index' {
  declare module.exports: $Exports<'react-dates-onidata/esm'>;
}
declare module 'react-dates-onidata/esm/index.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm'>;
}
declare module 'react-dates-onidata/esm/initialize.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/initialize'>;
}
declare module 'react-dates-onidata/esm/shapes/AnchorDirectionShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/shapes/AnchorDirectionShape'>;
}
declare module 'react-dates-onidata/esm/shapes/CalendarInfoPositionShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/shapes/CalendarInfoPositionShape'>;
}
declare module 'react-dates-onidata/esm/shapes/DateRangePickerShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/shapes/DateRangePickerShape'>;
}
declare module 'react-dates-onidata/esm/shapes/DayOfWeekShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/shapes/DayOfWeekShape'>;
}
declare module 'react-dates-onidata/esm/shapes/DisabledShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/shapes/DisabledShape'>;
}
declare module 'react-dates-onidata/esm/shapes/FocusedInputShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/shapes/FocusedInputShape'>;
}
declare module 'react-dates-onidata/esm/shapes/IconPositionShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/shapes/IconPositionShape'>;
}
declare module 'react-dates-onidata/esm/shapes/ModifiersShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/shapes/ModifiersShape'>;
}
declare module 'react-dates-onidata/esm/shapes/OpenDirectionShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/shapes/OpenDirectionShape'>;
}
declare module 'react-dates-onidata/esm/shapes/OrientationShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/shapes/OrientationShape'>;
}
declare module 'react-dates-onidata/esm/shapes/ScrollableOrientationShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/shapes/ScrollableOrientationShape'>;
}
declare module 'react-dates-onidata/esm/shapes/SingleDatePickerShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/shapes/SingleDatePickerShape'>;
}
declare module 'react-dates-onidata/esm/theme/DefaultTheme.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/theme/DefaultTheme'>;
}
declare module 'react-dates-onidata/esm/utils/calculateDimension.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/calculateDimension'>;
}
declare module 'react-dates-onidata/esm/utils/disableScroll.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/disableScroll'>;
}
declare module 'react-dates-onidata/esm/utils/getActiveElement.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/getActiveElement'>;
}
declare module 'react-dates-onidata/esm/utils/getCalendarDaySettings.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/getCalendarDaySettings'>;
}
declare module 'react-dates-onidata/esm/utils/getCalendarMonthWeeks.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/getCalendarMonthWeeks'>;
}
declare module 'react-dates-onidata/esm/utils/getCalendarMonthWidth.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/getCalendarMonthWidth'>;
}
declare module 'react-dates-onidata/esm/utils/getDetachedContainerStyles.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/getDetachedContainerStyles'>;
}
declare module 'react-dates-onidata/esm/utils/getInputHeight.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/getInputHeight'>;
}
declare module 'react-dates-onidata/esm/utils/getNumberOfCalendarMonthWeeks.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/getNumberOfCalendarMonthWeeks'>;
}
declare module 'react-dates-onidata/esm/utils/getPhrase.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/getPhrase'>;
}
declare module 'react-dates-onidata/esm/utils/getPhrasePropTypes.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/getPhrasePropTypes'>;
}
declare module 'react-dates-onidata/esm/utils/getPooledMoment.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/getPooledMoment'>;
}
declare module 'react-dates-onidata/esm/utils/getPreviousMonthMemoLast.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/getPreviousMonthMemoLast'>;
}
declare module 'react-dates-onidata/esm/utils/getResponsiveContainerStyles.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/getResponsiveContainerStyles'>;
}
declare module 'react-dates-onidata/esm/utils/getSelectedDateOffset.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/getSelectedDateOffset'>;
}
declare module 'react-dates-onidata/esm/utils/getTransformStyles.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/getTransformStyles'>;
}
declare module 'react-dates-onidata/esm/utils/getVisibleDays.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/getVisibleDays'>;
}
declare module 'react-dates-onidata/esm/utils/isAfterDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/isAfterDay'>;
}
declare module 'react-dates-onidata/esm/utils/isBeforeDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/isBeforeDay'>;
}
declare module 'react-dates-onidata/esm/utils/isDayVisible.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/isDayVisible'>;
}
declare module 'react-dates-onidata/esm/utils/isInclusivelyAfterDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/isInclusivelyAfterDay'>;
}
declare module 'react-dates-onidata/esm/utils/isInclusivelyBeforeDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/isInclusivelyBeforeDay'>;
}
declare module 'react-dates-onidata/esm/utils/isNextDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/isNextDay'>;
}
declare module 'react-dates-onidata/esm/utils/isNextMonth.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/isNextMonth'>;
}
declare module 'react-dates-onidata/esm/utils/isPrevMonth.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/isPrevMonth'>;
}
declare module 'react-dates-onidata/esm/utils/isSameDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/isSameDay'>;
}
declare module 'react-dates-onidata/esm/utils/isSameMonth.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/isSameMonth'>;
}
declare module 'react-dates-onidata/esm/utils/isTransitionEndSupported.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/isTransitionEndSupported'>;
}
declare module 'react-dates-onidata/esm/utils/modifiers.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/modifiers'>;
}
declare module 'react-dates-onidata/esm/utils/noflip.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/noflip'>;
}
declare module 'react-dates-onidata/esm/utils/registerCSSInterfaceWithDefaultTheme.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/registerCSSInterfaceWithDefaultTheme'>;
}
declare module 'react-dates-onidata/esm/utils/registerInterfaceWithDefaultTheme.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/registerInterfaceWithDefaultTheme'>;
}
declare module 'react-dates-onidata/esm/utils/toISODateString.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/toISODateString'>;
}
declare module 'react-dates-onidata/esm/utils/toISOMonthString.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/toISOMonthString'>;
}
declare module 'react-dates-onidata/esm/utils/toLocalizedDateString.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/toLocalizedDateString'>;
}
declare module 'react-dates-onidata/esm/utils/toMomentObject.js' {
  declare module.exports: $Exports<'react-dates-onidata/esm/utils/toMomentObject'>;
}
declare module 'react-dates-onidata/index' {
  declare module.exports: $Exports<'react-dates-onidata'>;
}
declare module 'react-dates-onidata/index.js' {
  declare module.exports: $Exports<'react-dates-onidata'>;
}
declare module 'react-dates-onidata/initialize.js' {
  declare module.exports: $Exports<'react-dates-onidata/initialize'>;
}
declare module 'react-dates-onidata/karma.conf.js' {
  declare module.exports: $Exports<'react-dates-onidata/karma.conf'>;
}
declare module 'react-dates-onidata/lib/components/CalendarDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/CalendarDay'>;
}
declare module 'react-dates-onidata/lib/components/CalendarIcon.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/CalendarIcon'>;
}
declare module 'react-dates-onidata/lib/components/CalendarMonth.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/CalendarMonth'>;
}
declare module 'react-dates-onidata/lib/components/CalendarMonthGrid.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/CalendarMonthGrid'>;
}
declare module 'react-dates-onidata/lib/components/CalendarWeek.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/CalendarWeek'>;
}
declare module 'react-dates-onidata/lib/components/ChevronDown.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/ChevronDown'>;
}
declare module 'react-dates-onidata/lib/components/ChevronUp.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/ChevronUp'>;
}
declare module 'react-dates-onidata/lib/components/CloseButton.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/CloseButton'>;
}
declare module 'react-dates-onidata/lib/components/CustomizableCalendarDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/CustomizableCalendarDay'>;
}
declare module 'react-dates-onidata/lib/components/DateInput.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/DateInput'>;
}
declare module 'react-dates-onidata/lib/components/DateRangePicker.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/DateRangePicker'>;
}
declare module 'react-dates-onidata/lib/components/DateRangePickerInput.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/DateRangePickerInput'>;
}
declare module 'react-dates-onidata/lib/components/DateRangePickerInputController.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/DateRangePickerInputController'>;
}
declare module 'react-dates-onidata/lib/components/DayPicker.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/DayPicker'>;
}
declare module 'react-dates-onidata/lib/components/DayPickerKeyboardShortcuts.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/DayPickerKeyboardShortcuts'>;
}
declare module 'react-dates-onidata/lib/components/DayPickerNavigation.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/DayPickerNavigation'>;
}
declare module 'react-dates-onidata/lib/components/DayPickerRangeController.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/DayPickerRangeController'>;
}
declare module 'react-dates-onidata/lib/components/DayPickerSingleDateController.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/DayPickerSingleDateController'>;
}
declare module 'react-dates-onidata/lib/components/KeyboardShortcutRow.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/KeyboardShortcutRow'>;
}
declare module 'react-dates-onidata/lib/components/LeftArrow.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/LeftArrow'>;
}
declare module 'react-dates-onidata/lib/components/RightArrow.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/RightArrow'>;
}
declare module 'react-dates-onidata/lib/components/SingleDatePicker.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/SingleDatePicker'>;
}
declare module 'react-dates-onidata/lib/components/SingleDatePickerInput.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/SingleDatePickerInput'>;
}
declare module 'react-dates-onidata/lib/components/SingleDatePickerInputController.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/components/SingleDatePickerInputController'>;
}
declare module 'react-dates-onidata/lib/constants.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/constants'>;
}
declare module 'react-dates-onidata/lib/defaultPhrases.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/defaultPhrases'>;
}
declare module 'react-dates-onidata/lib/index' {
  declare module.exports: $Exports<'react-dates-onidata/lib'>;
}
declare module 'react-dates-onidata/lib/index.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib'>;
}
declare module 'react-dates-onidata/lib/initialize.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/initialize'>;
}
declare module 'react-dates-onidata/lib/shapes/AnchorDirectionShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/shapes/AnchorDirectionShape'>;
}
declare module 'react-dates-onidata/lib/shapes/CalendarInfoPositionShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/shapes/CalendarInfoPositionShape'>;
}
declare module 'react-dates-onidata/lib/shapes/DateRangePickerShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/shapes/DateRangePickerShape'>;
}
declare module 'react-dates-onidata/lib/shapes/DayOfWeekShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/shapes/DayOfWeekShape'>;
}
declare module 'react-dates-onidata/lib/shapes/DisabledShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/shapes/DisabledShape'>;
}
declare module 'react-dates-onidata/lib/shapes/FocusedInputShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/shapes/FocusedInputShape'>;
}
declare module 'react-dates-onidata/lib/shapes/IconPositionShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/shapes/IconPositionShape'>;
}
declare module 'react-dates-onidata/lib/shapes/ModifiersShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/shapes/ModifiersShape'>;
}
declare module 'react-dates-onidata/lib/shapes/OpenDirectionShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/shapes/OpenDirectionShape'>;
}
declare module 'react-dates-onidata/lib/shapes/OrientationShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/shapes/OrientationShape'>;
}
declare module 'react-dates-onidata/lib/shapes/ScrollableOrientationShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/shapes/ScrollableOrientationShape'>;
}
declare module 'react-dates-onidata/lib/shapes/SingleDatePickerShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/shapes/SingleDatePickerShape'>;
}
declare module 'react-dates-onidata/lib/theme/DefaultTheme.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/theme/DefaultTheme'>;
}
declare module 'react-dates-onidata/lib/utils/calculateDimension.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/calculateDimension'>;
}
declare module 'react-dates-onidata/lib/utils/disableScroll.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/disableScroll'>;
}
declare module 'react-dates-onidata/lib/utils/getActiveElement.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/getActiveElement'>;
}
declare module 'react-dates-onidata/lib/utils/getCalendarDaySettings.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/getCalendarDaySettings'>;
}
declare module 'react-dates-onidata/lib/utils/getCalendarMonthWeeks.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/getCalendarMonthWeeks'>;
}
declare module 'react-dates-onidata/lib/utils/getCalendarMonthWidth.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/getCalendarMonthWidth'>;
}
declare module 'react-dates-onidata/lib/utils/getDetachedContainerStyles.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/getDetachedContainerStyles'>;
}
declare module 'react-dates-onidata/lib/utils/getInputHeight.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/getInputHeight'>;
}
declare module 'react-dates-onidata/lib/utils/getNumberOfCalendarMonthWeeks.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/getNumberOfCalendarMonthWeeks'>;
}
declare module 'react-dates-onidata/lib/utils/getPhrase.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/getPhrase'>;
}
declare module 'react-dates-onidata/lib/utils/getPhrasePropTypes.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/getPhrasePropTypes'>;
}
declare module 'react-dates-onidata/lib/utils/getPooledMoment.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/getPooledMoment'>;
}
declare module 'react-dates-onidata/lib/utils/getPreviousMonthMemoLast.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/getPreviousMonthMemoLast'>;
}
declare module 'react-dates-onidata/lib/utils/getResponsiveContainerStyles.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/getResponsiveContainerStyles'>;
}
declare module 'react-dates-onidata/lib/utils/getSelectedDateOffset.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/getSelectedDateOffset'>;
}
declare module 'react-dates-onidata/lib/utils/getTransformStyles.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/getTransformStyles'>;
}
declare module 'react-dates-onidata/lib/utils/getVisibleDays.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/getVisibleDays'>;
}
declare module 'react-dates-onidata/lib/utils/isAfterDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/isAfterDay'>;
}
declare module 'react-dates-onidata/lib/utils/isBeforeDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/isBeforeDay'>;
}
declare module 'react-dates-onidata/lib/utils/isDayVisible.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/isDayVisible'>;
}
declare module 'react-dates-onidata/lib/utils/isInclusivelyAfterDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/isInclusivelyAfterDay'>;
}
declare module 'react-dates-onidata/lib/utils/isInclusivelyBeforeDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/isInclusivelyBeforeDay'>;
}
declare module 'react-dates-onidata/lib/utils/isNextDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/isNextDay'>;
}
declare module 'react-dates-onidata/lib/utils/isNextMonth.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/isNextMonth'>;
}
declare module 'react-dates-onidata/lib/utils/isPrevMonth.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/isPrevMonth'>;
}
declare module 'react-dates-onidata/lib/utils/isSameDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/isSameDay'>;
}
declare module 'react-dates-onidata/lib/utils/isSameMonth.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/isSameMonth'>;
}
declare module 'react-dates-onidata/lib/utils/isTransitionEndSupported.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/isTransitionEndSupported'>;
}
declare module 'react-dates-onidata/lib/utils/modifiers.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/modifiers'>;
}
declare module 'react-dates-onidata/lib/utils/noflip.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/noflip'>;
}
declare module 'react-dates-onidata/lib/utils/registerCSSInterfaceWithDefaultTheme.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/registerCSSInterfaceWithDefaultTheme'>;
}
declare module 'react-dates-onidata/lib/utils/registerInterfaceWithDefaultTheme.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/registerInterfaceWithDefaultTheme'>;
}
declare module 'react-dates-onidata/lib/utils/toISODateString.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/toISODateString'>;
}
declare module 'react-dates-onidata/lib/utils/toISOMonthString.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/toISOMonthString'>;
}
declare module 'react-dates-onidata/lib/utils/toLocalizedDateString.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/toLocalizedDateString'>;
}
declare module 'react-dates-onidata/lib/utils/toMomentObject.js' {
  declare module.exports: $Exports<'react-dates-onidata/lib/utils/toMomentObject'>;
}
declare module 'react-dates-onidata/scripts/buildCSS.js' {
  declare module.exports: $Exports<'react-dates-onidata/scripts/buildCSS'>;
}
declare module 'react-dates-onidata/scripts/pure-component-fallback.js' {
  declare module.exports: $Exports<'react-dates-onidata/scripts/pure-component-fallback'>;
}
declare module 'react-dates-onidata/scripts/renderAllComponents.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/scripts/renderAllComponents'>;
}
declare module 'react-dates-onidata/src/components/CalendarDay.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/CalendarDay'>;
}
declare module 'react-dates-onidata/src/components/CalendarIcon.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/CalendarIcon'>;
}
declare module 'react-dates-onidata/src/components/CalendarMonth.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/CalendarMonth'>;
}
declare module 'react-dates-onidata/src/components/CalendarMonthGrid.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/CalendarMonthGrid'>;
}
declare module 'react-dates-onidata/src/components/CalendarWeek.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/CalendarWeek'>;
}
declare module 'react-dates-onidata/src/components/ChevronDown.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/ChevronDown'>;
}
declare module 'react-dates-onidata/src/components/ChevronUp.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/ChevronUp'>;
}
declare module 'react-dates-onidata/src/components/CloseButton.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/CloseButton'>;
}
declare module 'react-dates-onidata/src/components/CustomizableCalendarDay.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/CustomizableCalendarDay'>;
}
declare module 'react-dates-onidata/src/components/DateInput.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/DateInput'>;
}
declare module 'react-dates-onidata/src/components/DateRangePicker.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/DateRangePicker'>;
}
declare module 'react-dates-onidata/src/components/DateRangePickerInput.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/DateRangePickerInput'>;
}
declare module 'react-dates-onidata/src/components/DateRangePickerInputController.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/DateRangePickerInputController'>;
}
declare module 'react-dates-onidata/src/components/DayPicker.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/DayPicker'>;
}
declare module 'react-dates-onidata/src/components/DayPickerKeyboardShortcuts.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/DayPickerKeyboardShortcuts'>;
}
declare module 'react-dates-onidata/src/components/DayPickerNavigation.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/DayPickerNavigation'>;
}
declare module 'react-dates-onidata/src/components/DayPickerRangeController.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/DayPickerRangeController'>;
}
declare module 'react-dates-onidata/src/components/DayPickerSingleDateController.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/DayPickerSingleDateController'>;
}
declare module 'react-dates-onidata/src/components/KeyboardShortcutRow.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/KeyboardShortcutRow'>;
}
declare module 'react-dates-onidata/src/components/LeftArrow.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/LeftArrow'>;
}
declare module 'react-dates-onidata/src/components/RightArrow.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/RightArrow'>;
}
declare module 'react-dates-onidata/src/components/SingleDatePicker.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/SingleDatePicker'>;
}
declare module 'react-dates-onidata/src/components/SingleDatePickerInput.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/SingleDatePickerInput'>;
}
declare module 'react-dates-onidata/src/components/SingleDatePickerInputController.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/components/SingleDatePickerInputController'>;
}
declare module 'react-dates-onidata/src/constants.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/constants'>;
}
declare module 'react-dates-onidata/src/defaultPhrases.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/defaultPhrases'>;
}
declare module 'react-dates-onidata/src/index' {
  declare module.exports: $Exports<'react-dates-onidata/src'>;
}
declare module 'react-dates-onidata/src/index.js' {
  declare module.exports: $Exports<'react-dates-onidata/src'>;
}
declare module 'react-dates-onidata/src/initialize.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/initialize'>;
}
declare module 'react-dates-onidata/src/shapes/AnchorDirectionShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/shapes/AnchorDirectionShape'>;
}
declare module 'react-dates-onidata/src/shapes/CalendarInfoPositionShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/shapes/CalendarInfoPositionShape'>;
}
declare module 'react-dates-onidata/src/shapes/DateRangePickerShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/shapes/DateRangePickerShape'>;
}
declare module 'react-dates-onidata/src/shapes/DayOfWeekShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/shapes/DayOfWeekShape'>;
}
declare module 'react-dates-onidata/src/shapes/DisabledShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/shapes/DisabledShape'>;
}
declare module 'react-dates-onidata/src/shapes/FocusedInputShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/shapes/FocusedInputShape'>;
}
declare module 'react-dates-onidata/src/shapes/IconPositionShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/shapes/IconPositionShape'>;
}
declare module 'react-dates-onidata/src/shapes/ModifiersShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/shapes/ModifiersShape'>;
}
declare module 'react-dates-onidata/src/shapes/OpenDirectionShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/shapes/OpenDirectionShape'>;
}
declare module 'react-dates-onidata/src/shapes/OrientationShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/shapes/OrientationShape'>;
}
declare module 'react-dates-onidata/src/shapes/ScrollableOrientationShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/shapes/ScrollableOrientationShape'>;
}
declare module 'react-dates-onidata/src/shapes/SingleDatePickerShape.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/shapes/SingleDatePickerShape'>;
}
declare module 'react-dates-onidata/src/theme/DefaultTheme.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/theme/DefaultTheme'>;
}
declare module 'react-dates-onidata/src/utils/calculateDimension.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/calculateDimension'>;
}
declare module 'react-dates-onidata/src/utils/disableScroll.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/disableScroll'>;
}
declare module 'react-dates-onidata/src/utils/getActiveElement.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/getActiveElement'>;
}
declare module 'react-dates-onidata/src/utils/getCalendarDaySettings.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/getCalendarDaySettings'>;
}
declare module 'react-dates-onidata/src/utils/getCalendarMonthWeeks.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/getCalendarMonthWeeks'>;
}
declare module 'react-dates-onidata/src/utils/getCalendarMonthWidth.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/getCalendarMonthWidth'>;
}
declare module 'react-dates-onidata/src/utils/getDetachedContainerStyles.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/getDetachedContainerStyles'>;
}
declare module 'react-dates-onidata/src/utils/getInputHeight.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/getInputHeight'>;
}
declare module 'react-dates-onidata/src/utils/getNumberOfCalendarMonthWeeks.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/getNumberOfCalendarMonthWeeks'>;
}
declare module 'react-dates-onidata/src/utils/getPhrase.jsx' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/getPhrase'>;
}
declare module 'react-dates-onidata/src/utils/getPhrasePropTypes.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/getPhrasePropTypes'>;
}
declare module 'react-dates-onidata/src/utils/getPooledMoment.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/getPooledMoment'>;
}
declare module 'react-dates-onidata/src/utils/getPreviousMonthMemoLast.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/getPreviousMonthMemoLast'>;
}
declare module 'react-dates-onidata/src/utils/getResponsiveContainerStyles.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/getResponsiveContainerStyles'>;
}
declare module 'react-dates-onidata/src/utils/getSelectedDateOffset.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/getSelectedDateOffset'>;
}
declare module 'react-dates-onidata/src/utils/getTransformStyles.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/getTransformStyles'>;
}
declare module 'react-dates-onidata/src/utils/getVisibleDays.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/getVisibleDays'>;
}
declare module 'react-dates-onidata/src/utils/isAfterDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/isAfterDay'>;
}
declare module 'react-dates-onidata/src/utils/isBeforeDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/isBeforeDay'>;
}
declare module 'react-dates-onidata/src/utils/isDayVisible.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/isDayVisible'>;
}
declare module 'react-dates-onidata/src/utils/isInclusivelyAfterDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/isInclusivelyAfterDay'>;
}
declare module 'react-dates-onidata/src/utils/isInclusivelyBeforeDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/isInclusivelyBeforeDay'>;
}
declare module 'react-dates-onidata/src/utils/isNextDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/isNextDay'>;
}
declare module 'react-dates-onidata/src/utils/isNextMonth.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/isNextMonth'>;
}
declare module 'react-dates-onidata/src/utils/isPrevMonth.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/isPrevMonth'>;
}
declare module 'react-dates-onidata/src/utils/isSameDay.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/isSameDay'>;
}
declare module 'react-dates-onidata/src/utils/isSameMonth.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/isSameMonth'>;
}
declare module 'react-dates-onidata/src/utils/isTransitionEndSupported.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/isTransitionEndSupported'>;
}
declare module 'react-dates-onidata/src/utils/modifiers.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/modifiers'>;
}
declare module 'react-dates-onidata/src/utils/noflip.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/noflip'>;
}
declare module 'react-dates-onidata/src/utils/registerCSSInterfaceWithDefaultTheme.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/registerCSSInterfaceWithDefaultTheme'>;
}
declare module 'react-dates-onidata/src/utils/registerInterfaceWithDefaultTheme.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/registerInterfaceWithDefaultTheme'>;
}
declare module 'react-dates-onidata/src/utils/toISODateString.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/toISODateString'>;
}
declare module 'react-dates-onidata/src/utils/toISOMonthString.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/toISOMonthString'>;
}
declare module 'react-dates-onidata/src/utils/toLocalizedDateString.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/toLocalizedDateString'>;
}
declare module 'react-dates-onidata/src/utils/toMomentObject.js' {
  declare module.exports: $Exports<'react-dates-onidata/src/utils/toMomentObject'>;
}
