// flow-typed signature: 60d17e0ffc1f8e11b4d2a8bf9a605356
// flow-typed version: <<STUB>>/react-router-transition_v^2.0.0/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-transition'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-transition' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-transition/babel.config' {
  declare module.exports: any;
}

declare module 'react-router-transition/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-transition/babel.config.js' {
  declare module.exports: $Exports<'react-router-transition/babel.config'>;
}
declare module 'react-router-transition/index' {
  declare module.exports: $Exports<'react-router-transition'>;
}
declare module 'react-router-transition/index.js' {
  declare module.exports: $Exports<'react-router-transition'>;
}
declare module 'react-router-transition/lib/index' {
  declare module.exports: $Exports<'react-router-transition/lib'>;
}
declare module 'react-router-transition/lib/index.js' {
  declare module.exports: $Exports<'react-router-transition/lib'>;
}
