// flow-typed signature: 3cb0e7ee1f430b9cb1a2e5eea6f6cad7
// flow-typed version: <<STUB>>/redux-form-input-masks_v^1.3.0/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-form-input-masks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-form-input-masks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-form-input-masks/dist/bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-form-input-masks/dist/bundle.js' {
  declare module.exports: $Exports<'redux-form-input-masks/dist/bundle'>;
}
