// flow-typed signature: f5d077a699a6817bd093128c9c017a66
// flow-typed version: <<STUB>>/webpack-fix-style-only-entries_v^0.4.0/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-fix-style-only-entries'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-fix-style-only-entries' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-fix-style-only-entries/index' {
  declare module.exports: $Exports<'webpack-fix-style-only-entries'>;
}
declare module 'webpack-fix-style-only-entries/index.js' {
  declare module.exports: $Exports<'webpack-fix-style-only-entries'>;
}
