// @flow

// Redux Form
export type REDUX_FORM_SUBMIT = '@@redux-form/START_SUBMIT'
export type REDUX_FORM_CHANGE = '@@redux-form/CHANGE'

export type REACT_ROUTER_LOCATION_CHANGE = '@@router/LOCATION_CHANGE'

// App
export type APP_LOAD_SPINNER = 'CORE/APP_LOAD_SPINNER'
export type APP_UNLOAD_SPINNER = 'CORE/APP_UNLOAD_SPINNER'

// Exceptions
export type EXCEPTION_SAVE = 'CORE/EXCEPTION_SAVE'
export type EXCEPTION_CLEAR = 'CORE/EXCEPTION_CLEAR'

export type TActionTypes = REDUX_FORM_SUBMIT
  | REDUX_FORM_CHANGE
  | APP_LOAD_SPINNER
  | APP_UNLOAD_SPINNER
  | EXCEPTION_SAVE
  | EXCEPTION_CLEAR
  | REACT_ROUTER_LOCATION_CHANGE
