// flow-typed signature: 5f1957a8a7494ee2e7fc2cda9bb75260
// flow-typed version: <<STUB>>/@testing-library/cypress_v^5.0.1/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/cypress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/cypress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@testing-library/cypress/add-commands' {
  declare module.exports: any;
}

declare module '@testing-library/cypress/dist/add-commands' {
  declare module.exports: any;
}

declare module '@testing-library/cypress/dist' {
  declare module.exports: any;
}

declare module '@testing-library/cypress/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@testing-library/cypress/add-commands.js' {
  declare module.exports: $Exports<'@testing-library/cypress/add-commands'>;
}
declare module '@testing-library/cypress/dist/add-commands.js' {
  declare module.exports: $Exports<'@testing-library/cypress/dist/add-commands'>;
}
declare module '@testing-library/cypress/dist/index' {
  declare module.exports: $Exports<'@testing-library/cypress/dist'>;
}
declare module '@testing-library/cypress/dist/index.js' {
  declare module.exports: $Exports<'@testing-library/cypress/dist'>;
}
declare module '@testing-library/cypress/dist/utils.js' {
  declare module.exports: $Exports<'@testing-library/cypress/dist/utils'>;
}
